root: true
extends:
  - 'portsoc'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  browser: true
  node: true
rules:
  -import/no-unresolved: off
